### ISSUE TITLE
Lua redundant loop step

### ISSUE THREAD

**Issue by MeWhenI** [jared-hughes/polygolf#132]
**Language**
Lua

**Polygolf source**

```
for $i 1 10{
 $j <- $i;
};
```

**Current output**

```
for i=1,9,1 do j=i end
```

**Expected output**

```
for i=1,9 do j=i end
```

**Comment**
Output is correct but longer than it should be. This appears to be the result of a recent change, as the bot has submitted shorter solutions than what it is currently generating.

**Comment by MichalMarsalek** [comment]
This is fixed as part of #121 .
