### ISSUE TITLE
Golfscript: range doesn't work properly with negatives

### ISSUE THREAD

**Issue by Steffan153** [jared-hughes/polygolf#141]
`for $b -15 1` compiles to `1,-15>` which obviously doesn't work.

**Comment by MichalMarsalek** [comment]
> `for $b -15 1` compiles to `1,-15>` which obviously doesn't work.

Please show valid Polygolf, current output and expected output for the bug reports (don't delete the template).

**Comment by Steffan153** [comment]
Correct output here would be `16,{15-}%`.
