### ISSUE TITLE
Automatically convert exclusive ranges to inclusive

### ISSUE THREAD

**Issue by Steffan153** [jared-hughes/polygolf#144]
In my code, I have `for $j 1 ($i + 1)`. In nim, it compiles to this:
```nim
for j in 1..<i+1:
```
This should of course be `1..i`. Same in swift with `for j in 1..<i+1` which should be `for j in 1...i`.
The worst though, is in Lua:
```lua
for j=1,i+1-1,1 do
```
Literally what lmao.

**Comment by MichalMarsalek** [comment]
Yeah, I know about this, I have it fixed some of my branches.
