### ISSUE TITLE
Nim - indexless for loop

### ISSUE THREAD

**Issue by MichalMarsalek** [jared-hughes/polygolf#228]
Emit
```
for $i 0 10 {println "x";};
```
to
```nim
for()in..9:echo"x"
```
in Nim

**Comment by btnlq** [comment]
Emit
```
for 10 {...};
```
to
```py
for _ in' '*10:... # python
```
```nim
for()in..9:... # nim
```
```c++
for(int k=10;k--;){...} // c++
```

**Comment by MichalMarsalek** [comment]
> ```python
> for _ in' '*10:... # python
> exec("...;"*10) # python, but might be too hard to implement
> ```

I actually had the 2nd version WIP somewhere I think, but I forgot about the first one, thanks!
