### ISSUE TITLE
Invalid substitution in Python

### ISSUE THREAD

**Issue by MeWhenI** [jared-hughes/polygolf#235]
**Describe the bug**
The python generator may erroneously attempt to create an alias of the string `join` method.

**To Reproduce**
Compiling
```polygolf
$a <- (join (list "1" "2") );
$b <- (join (list "3" "4") );
$c <- (join (list "5" "6") );
```
to Python produces
```python
j=join
a="".j(["1","2"])
b="".j(["3","4"])
c="".j(["5","6"])
```

**Expected behavior**
We can tell it not to alias `join` and simply produce
```python
a="".join(["1","2"])
b="".join(["3","4"])
c="".join(["5","6"])
```
although as I just discovered while creating this bug report, this is valid code:
```python
j="".join
a=j(["1","2"])
b=j(["3","4"])
c=j(["5","6"])
```

**Comment by MichalMarsalek** [comment]
The goal was to generate the code from your last snippet, I am actually shocked that I didn't  add a test for this and that it generated the nonsense that it does.
