### ISSUE TITLE
Traversal only visits 9 children.

### ISSUE THREAD

**Issue by MeWhenI** [jared-hughes/polygolf#28]
Attempting to build the following polyglot code into Lua gives the error ` Lua requires inclusive ForRange`.

```
$a <- 1;
$a <- 1;
$a <- 1;
$a <- 1;
$a <- 1;
$a <- 1;
$a <- 1;
$a <- 1;
$a <- 1;
for $b 1 10 {
};
```

Removing one or more of the assignments fixes the error, but it seems having 9 or more assignments causes a bug.

**Comment by MichalMarsalek** [comment]
Hmm, this is quite peculiar.

**Comment by MichalMarsalek** [comment]
Ah uh
https://github.com/jared-hughes/polygolf/blob/main/src/common/traverse.ts#L131
@jared-hughes

**Comment by jared-hughes** [comment]
Looks like I put a limit on it while debugging some infinite loop, and never took it off. Though based on the block comment, an infinite loop is still possible if plugin code is written incorrectly. So I'll raise the limit to something large like 10000, and throw an error if it's hit.
