### ISSUE TITLE
Distinguish treatment of bytes and characters

### ISSUE THREAD

**Issue by MeWhenI** [jared-hughes/polygolf#51]
There is not a default behavior for `text-length`; replacing it with 2 new ops, `text-length-bytes` and `text-length-chars` reduces ambiguity. Same situation for `text-get-slice`

**Comment by MichalMarsalek** [comment]
Also, what does the length limit of the actual Text type measure? I think I'd prefer codepoints.

**Comment by MichalMarsalek** [comment]
Is byte_to_char useful? Should it instead be int_to_char to get any Unicode codepoint?
