### ISSUE TITLE
Python print without newline

### ISSUE THREAD

**Issue by MeWhenI** [jared-hughes/polygolf#54]
Compiling
```
print 1;
println 1;
```
to Python produces
```py
print(end=1)
print(1)
```
The first line produces a typeError because the `end` argument must be a string. (The second print is only there so the `golfLastPrint` plugin isn't run on the first print.)

**Comment by MichalMarsalek** [comment]
We should decide if it should even type check in Polygolf or if explicit conversion to string should be required.
