### ISSUE TITLE
Nim method parenthesization

### ISSUE THREAD

**Issue by MeWhenI** [jared-hughes/polygolf#56]
Compiling
```
print (text_split "abc" "b");
```
to Nim produces
```Nim
include re
"abc".split "b".echo
```
which throws a type error

**Comment by MichalMarsalek** [comment]
Might be worth it to introduce two new binary ops, `call` and `inverted_call` to handle the precedence of ` ` and `.` instead of doing it add hoc (stuff like `expressionContinues`).

**Comment by Steffan153** [comment]
of course, since we're trying to golf this, producing `echo "abc".split "b"` would be the optimal behavior

**Comment by MichalMarsalek** [comment]
> of course, since we're trying to golf this, producing `echo "abc".split "b"` would be the optimal behavior

Actually, both `echo "abc".split"b"` and `"abc".split"b".echo` are both correct and 1 byte shorter.
