### ISSUE TITLE
Allow compiling to all languages at once

### ISSUE THREAD

**Issue by Steffan153** [jared-hughes/polygolf#63]
So do like `polygolf -i src/programs/fibonacci.polygolf -l all -o fibonacci` and it will output to `fibonacci.lua`, `fibonacci.nim`, etc.

Another possible thing is that instead of having `-o fibonacci`, you can have an option like `--cg` that will automatically upload everything to code.golf (of course, you have to input your token or whatever).

**Comment by MichalMarsalek** [comment]
> Another possible thing is that instead of having `-o fibonacci`, you can have an option like `--cg` that will automatically upload everything to code.golf (of course, you have to input your token or whatever).

You can use https://github.com/jared-hughes/golfc for submitting solutions, we won't be intergrating this into polygolf.
