### ISSUE TITLE
When applying an operation to a variable in a loop, Polygolf tries to replace it with a pre-calculated expression

### ISSUE THREAD

**Issue by Steffan153** [jared-hughes/polygolf#67]
For example this code:
```
$s <- 5;
println $s;
$s <- ($s * $s);
println $s;
```
Compiles correctly into something like this:
```lua
s=5
print(s)
s=25
print(s)
```

But it still does this even if we do it in a loop:
```
$s <- 5;

for $i 0 5 {
  $s <- ($s * $s);
  println $s;
};
```
=>
```lua
s=5
for i=0,4 do s=25
print(s)end
```

**Comment by MichalMarsalek** [comment]
The correct behaviour should be throwing a type error.

$s is missing a type annotation so it's type should be inferred to `5..5`
Then, an expression, with the type of `25..25` is being assigned to the variable `$s:5..5`.

**Comment by MichalMarsalek** [comment]
The assignment is never typecheckd now.

```
$s <- 5;
$s <- "x";
```

Doesn't throw.
